spring:
   datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Yjh@rs05
      type: com.alibaba.druid.pool.DruidDataSource


## Mybatis 配置
mybatis:
  typeAliasesPackage: jhclass.entity
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##日志
logging:
  level:
    jhclass.dao: DEBUG
    org.springframework: DEBUG